name: island
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  rxdart: ^0.24.1
  dio: ^3.0.9
  shared_preferences: ^0.5.10
  video_player: ^0.10.12+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/updateguide1.png
    - assets/images/updateguide2.png
    - assets/images/updateguide3.png
    - assets/images/updateguide4.png
    - assets/images/updateguide5.png
    - assets/images/updateguide6.png
    - assets/images/me_bg_a.png
    - assets/images/me_bg_b.png
    - assets/images/me_top_bg.png
    - assets/images/login_bottom_icon.png
    - assets/images/setting_icon.png
    - assets/images/main_me.png
    - assets/images/main_main.png
    - assets/images/main_conversation.png
    - assets/images/maindrift_hasnews.png
    - assets/images/main_randomplay.png
    - assets/images/maindrift_normal.png
    - assets/images/ic_topic.png
    - assets/images/item_feedadapter_talk.png
    - assets/images/love_normal.png
    - assets/images/love_normal_feed_detail.png
    - assets/images/loveanimation.png
    - assets/images/love_press_water_fall.png
    - assets/images/img_url_right.png
    - assets/images/picture_icon_video_play.png
    - assets/images/ic_interaction_follow.png
    - assets/images/ic_interaction_love.png
    - assets/images/ic_interaction_comment.png
    - assets/images/ic_interaction_favorite.png
    - assets/images/login_bottom_light.png
    - assets/images/img_splash_top.png
    - assets/images/start_text.png
    - assets/images/white_back_icon.png
    - assets/images/feeddetali_more.png

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/font/iconfont.ttf